### ISSUE TITLE
Redirect after switching perspective

### ISSUE THREAD

**Issue by mateusz-peczkowski** [Muetze42/nova-perspectives#11]
Hi. This is a great package. 

I've used it to build a multisite website admin panel which works great BUT there is one thing.

Is there an option for me to hook into action when the perspective changes and redirect users to one "common" resource that all my websites have (so pages)?

If not then I am receiving 403 as if you are in details of resource like page ID 1 which exists on perspective and you will switch perspective you will get 403 AS page ID 1 not exists on perspective-2 ;)

**Comment by Muetze42** [comment]
Thanks for the pull request. I'm short of time at the moment, so I'm happy about every commit instead of a feature request.

I have created a release with the changes.
