### ISSUE TITLE
Support/NovaPerspectivesCollection does not contain 'use ReflectionClass'

### ISSUE THREAD

**Issue by webard** [Muetze42/nova-perspectives#8]
https://github.com/Muetze42/nova-perspectives/blob/33beac1134a94fa1e11261c48d9cc5fb889e0fb3/src/Support/NovaPerspectivesCollection.php

In that file there is no

```
use ReflectionClass;
```

statement, causing fatal error.

**Comment by Muetze42** [comment]
Thanks. Update is released
https://github.com/Muetze42/nova-perspectives/releases
